# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a8e776349e78ab813c5b80b3af5e71c5a65a3423b535b6efe12e9b4053057089352581bce42f494f20783d9367d27d2fd96ccdba47c63090c64c46d6b40cf9d

test:
  secret_key_base: 41ac6ca3b0e789f804002ff587bb8f593fc7d6fcb0f48a4f72c0331b894fa4097ec2fee1ed7490f997735310fed6b17b261462f8a0ee0d5adab3227afafd2678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1bd2cdf7104348c170b7082c3c0a6c14c48ddca759e7e1f9a53e1bbbd18ffbb52197fed3720725765062f9d7b34e61a3e3a86c2a364762d87336d41f5632baa8
